services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: tesla
      POSTGRES_PASSWORD: tesla
      POSTGRES_DB: tesla_rental
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
